-- =============================================
-- Fichier de crÃ©ation de la base de donnÃ©es
-- Smart Summer Club
-- Version: 2.0
-- Date: 09/12/2025
-- =============================================

-- DÃ©sactivation des contraintes de clÃ© Ã©trangÃ¨re temporairement
ALTER SESSION SET CONSTRAINTS = DEFERRED;

-- Suppression des dÃ©clencheurs
BEGIN
    FOR r_trigger IN (SELECT trigger_name FROM user_triggers) LOOP
        EXECUTE IMMEDIATE 'DROP TRIGGER ' || r_trigger.trigger_name;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lors de la suppression des triggers: ' || SQLERRM);
END;
/

-- Suppression des contraintes de clÃ© Ã©trangÃ¨re
BEGIN
    FOR r_constraint IN (SELECT table_name, constraint_name 
                        FROM user_constraints 
                        WHERE constraint_type = 'R') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || r_constraint.table_name || 
                         ' DROP CONSTRAINT ' || r_constraint.constraint_name;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lors de la suppression des contraintes: ' || SQLERRM);
END;
/

-- Suppression des tables
BEGIN
    FOR r_table IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || r_table.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lors de la suppression des tables: ' || SQLERRM);
END;
/

-- Suppression des sÃ©quences
BEGIN
    FOR r_sequence IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r_sequence.sequence_name;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lors de la suppression des sÃ©quences: ' || SQLERRM);
END;
/

-- =============================================
-- CrÃ©ation des sÃ©quences
-- =============================================
CREATE SEQUENCE SEQ_ID_ABONNE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_ACTIVITE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_INSCRIPTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_MATERIEL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_JOURNAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_UTILISATEUR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================
-- Table: ROLES
-- Gestion des rÃ´les utilisateurs
-- =============================================
CREATE TABLE ROLES (
    ID_ROLE NUMBER PRIMARY KEY,
    CODE_ROLE VARCHAR2(20) NOT NULL UNIQUE,
    LIBELLE VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DATE_CREATION TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATE_MODIFICATION TIMESTAMP,
    EST_ACTIF CHAR(1) DEFAULT 'Y',
    CONSTRAINT CHK_ROLE_ACTIF CHECK (EST_ACTIF IN ('Y', 'N'))
);

-- =============================================
-- Table: UTILISATEURS
-- Gestion des comptes utilisateurs
-- =============================================
CREATE TABLE UTILISATEURS (
    ID_UTILISATEUR NUMBER PRIMARY KEY,
    NOM_UTILISATEUR VARCHAR2(50) NOT NULL UNIQUE,
    MOT_DE_PASSE_HASH VARCHAR2(256) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    DATE_CREATION TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATE_DERNIERE_CONNEXION TIMESTAMP,
    COMPTE_ACTIF CHAR(1) DEFAULT 'Y',
    COMPTE_VERROUILLE CHAR(1) DEFAULT 'N',
    NOMBRE_TENTATIVES NUMBER(2) DEFAULT 0,
    DATE_VERROUILLAGE TIMESTAMP,
    CONSTRAINT CHK_UTILISATEUR_ACTIF CHECK (COMPTE_ACTIF IN ('Y', 'N')),
    CONSTRAINT CHK_UTILISATEUR_VERROUILLE CHECK (COMPTE_VERROUILLE IN ('Y', 'N'))
);

-- =============================================
-- Table: UTILISATEURS_ROLES
-- Association des rÃ´les aux utilisateurs
-- =============================================
CREATE TABLE UTILISATEURS_ROLES (
    ID_UTILISATEUR NUMBER NOT NULL,
    ID_ROLE NUMBER NOT NULL,
    DATE_DEBUT DATE DEFAULT SYSDATE,
    DATE_FIN DATE,
    COMMENTAIRE VARCHAR2(500),
    CONSTRAINT PK_UTILISATEURS_ROLES PRIMARY KEY (ID_UTILISATEUR, ID_ROLE, DATE_DEBUT),
    CONSTRAINT FK_UR_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEURS(ID_UTILISATEUR),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE)
);

-- =============================================
-- Table: ABONNES
-- Gestion des abonnÃ©s du club
-- =============================================
CREATE TABLE ABONNES (
    ID_ABONNE NUMBER PRIMARY KEY,
    ID_UTILISATEUR NUMBER UNIQUE,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    DATE_NAISSANCE DATE NOT NULL,
    ADRESSE VARCHAR2(200),
    CODE_POSTAL VARCHAR2(10),
    VILLE VARCHAR2(100),
    PAYS VARCHAR2(100) DEFAULT 'Tunisie',
    TELEPHONE VARCHAR2(20),
    EMAIL VARCHAR2(100) UNIQUE,
    DATE_INSCRIPTION DATE DEFAULT SYSDATE,
    DATE_FIN_ABONNEMENT DATE,
    PHOTO_PROFIL BLOB,
    TYPE_PIECE_IDENTITE VARCHAR2(50),
    NUMERO_PIECE_IDENTITE VARCHAR2(50),
    SEXE CHAR(1),
    SITUATION_FAMILIALE VARCHAR2(50),
    PROFESSION VARCHAR2(100),
    CONTACT_URGENCE_NOM VARCHAR2(100),
    CONTACT_URGENCE_TEL VARCHAR2(20),
    CONTACT_URGENCE_LIEN VARCHAR2(50),
    EST_ACTIF CHAR(1) DEFAULT 'Y',
    CONSTRAINT CHK_ABONNE_ACTIF CHECK (EST_ACTIF IN ('Y', 'N')),
    CONSTRAINT CHK_SEXE CHECK (SEXE IN ('M', 'F', 'A')),
    CONSTRAINT FK_ABONNE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEURS(ID_UTILISATEUR)
);

-- =============================================
-- Table: ACTIVITES
-- Gestion des activitÃ©s proposÃ©es
-- =============================================
CREATE TABLE ACTIVITES (
    ID_ACTIVITE NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    DESCRIPTION CLOB,
    DUREE_SEANCE NUMBER,
    LIEU VARCHAR2(100),
    NB_PARTICIPANTS_MAX NUMBER,
    PRIX_BASE NUMBER(10, 2) NOT NULL,
    NIVEAU_DIFFICULTE VARCHAR2(20),
    AGE_MINIMUM NUMBER(2) DEFAULT 0,
    EST_ACTIVE CHAR(1) DEFAULT 'Y',
    DATE_DEBUT_SAISON DATE,
    DATE_FIN_SAISON DATE,
    HEURE_DEBUT VARCHAR2(5),
    HEURE_FIN VARCHAR2(5),
    JOURS_SEMAINE VARCHAR2(20),
    COULEUR_CALENDRIER VARCHAR2(7) DEFAULT '#3498db',
    CONSTRAINT CHK_ACTIVITE_ACTIVE CHECK (EST_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_NIVEAU_DIFFICULTE CHECK (NIVEAU_DIFFICULTE IN ('DÃ©butant', 'IntermÃ©diaire', 'AvancÃ©', 'Tous niveaux'))
);

-- =============================================
-- Table: EMPLOYES
-- Gestion du personnel
-- =============================================
CREATE TABLE EMPLOYES (
    ID_EMPLOYE NUMBER PRIMARY KEY,
    ID_UTILISATEUR NUMBER UNIQUE,
    CIN VARCHAR2(20) UNIQUE,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    POSTE VARCHAR2(100),
    GENRE CHAR(1),
    EMAIL VARCHAR2(100) UNIQUE,
    TELEPHONE VARCHAR2(20),
    DATE_NAISSANCE DATE,
    ADRESSE VARCHAR2(200),
    VILLE VARCHAR2(100),
    CODE_POSTAL VARCHAR2(10),
    PAYS VARCHAR2(100) DEFAULT 'Tunisie',
    SALAIRE_BASE NUMBER(12, 2),
    DATE_EMBAUCHE DATE,
    DATE_FIN_CONTRAT DATE,
    TYPE_CONTRAT VARCHAR2(50),
    NUMERO_SECURITE_SOCIALE VARCHAR2(50),
    BANQUE_NOM VARCHAR2(100),
    BANQUE_IBAN VARCHAR2(34),
    BANQUE_BIC VARCHAR2(11),
    EST_ACTIF CHAR(1) DEFAULT 'Y',
    PHOTO BLOB,
    SIGNATURE BLOB,
    CONSTRAINT CHK_EMPLOYE_ACTIF CHECK (EST_ACTIF IN ('Y', 'N')),
    CONSTRAINT CHK_GENRE CHECK (GENRE IN ('M', 'F', 'A')),
    CONSTRAINT FK_EMPLOYE_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEURS(ID_UTILISATEUR)
);

-- =============================================
-- Table: INSCRIPTIONS
-- Gestion des inscriptions aux activitÃ©s
-- =============================================
CREATE TABLE INSCRIPTIONS (
    ID_INSCRIPTION NUMBER PRIMARY KEY,
    ID_ABONNE NUMBER NOT NULL,
    ID_ACTIVITE NUMBER NOT NULL,
    ID_EMPLOYE NUMBER,
    DATE_INSCRIPTION TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATE_DEBUT DATE,
    DATE_FIN DATE,
    STATUT VARCHAR2(20) DEFAULT 'EN_ATTENTE' NOT NULL,
    PAIEMENT_EFFECTUE CHAR(1) DEFAULT 'N' NOT NULL,
    MODE_PAIEMENT VARCHAR2(50),
    DATE_PAIEMENT DATE,
    MONTANT_PAYE NUMBER(10, 2),
    REMISE NUMBER(5, 2) DEFAULT 0,
    PRIX_TOTAL NUMBER(10, 2) NOT NULL,
    FACTURE_GENERE CHAR(1) DEFAULT 'N',
    NUMERO_FACTURE VARCHAR2(50),
    COMMENTAIRE VARCHAR2(1000),
    DATE_ANNULATION DATE,
    MOTIF_ANNULATION VARCHAR2(500),
    CONSTRAINT CHK_INSCRIPTION_STATUT CHECK (STATUT IN ('EN_ATTENTE', 'CONFIRME', 'ANNULE', 'TERMINE', 'EN_COURS')),
    CONSTRAINT CHK_PAIEMENT_EFFECTUE CHECK (PAIEMENT_EFFECTUE IN ('Y', 'N')),
    CONSTRAINT CHK_FACTURE_GENERE CHECK (FACTURE_GENERE IN ('Y', 'N')),
    CONSTRAINT FK_INSCRIPTION_ABONNE FOREIGN KEY (ID_ABONNE) REFERENCES ABONNES(ID_ABONNE),
    CONSTRAINT FK_INSCRIPTION_ACTIVITE FOREIGN KEY (ID_ACTIVITE) REFERENCES ACTIVITES(ID_ACTIVITE),
    CONSTRAINT FK_INSCRIPTION_EMPLOYE FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYES(ID_EMPLOYE)
);

-- =============================================
-- Table: MATERIELS
-- Gestion du matÃ©riel
-- =============================================
CREATE TABLE MATERIELS (
    ID_MATERIEL NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CATEGORIE VARCHAR2(100),
    MARQUE VARCHAR2(100),
    MODELE VARCHAR2(100),
    NUMERO_SERIE VARCHAR2(100),
    QUANTITE_TOTALE NUMBER NOT NULL,
    QUANTITE_DISPONIBLE NUMBER,
    ETAT VARCHAR2(50),
    FOURNISSEUR VARCHAR2(100),
    ID_FOURNISSEUR VARCHAR2(50),
    DATE_ACHAT DATE,
    DUREE_GARANTIE_MOIS NUMBER,
    COUT_ACHAT_UNITAIRE NUMBER(10, 2),
    VALEUR_REMPLACEMENT NUMBER(10, 2),
    LOCALISATION VARCHAR2(100),
    DATE_DERNIERE_MAINTENANCE DATE,
    PROCHAINE_MAINTENANCE_PREVUE DATE,
    EST_LOUE CHAR(1) DEFAULT 'N',
    EST_MAINTENANCE CHAR(1) DEFAULT 'N',
    EST_ACTIF CHAR(1) DEFAULT 'Y',
    CONSTRAINT CHK_MATERIEL_LOUE CHECK (EST_LOUE IN ('Y', 'N')),
    CONSTRAINT CHK_MATERIEL_MAINTENANCE CHECK (EST_MAINTENANCE IN ('Y', 'N')),
    CONSTRAINT CHK_MATERIEL_ACTIF CHECK (EST_ACTIF IN ('Y', 'N'))
);

-- =============================================
-- Table: JOURNAUX_ACTIVITE
-- Journalisation des actions utilisateurs
-- =============================================
CREATE TABLE JOURNAUX_ACTIVITE (
    ID_JOURNAL NUMBER PRIMARY KEY,
    ID_UTILISATEUR NUMBER,
    DATE_HEURE_ACTION TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODULE VARCHAR2(50),
    ACTION VARCHAR2(100) NOT NULL,
    DETAILS CLOB,
    ADRESSE_IP VARCHAR2(45),
    NAVIGATEUR VARCHAR2(200),
    SYSTEME_EXPLOITATION VARCHAR2(100),
    EST_REUSSI CHAR(1) DEFAULT 'Y',
    MESSAGE_ERREUR CLOB,
    CONSTRAINT CHK_JOURNAL_REUSSI CHECK (EST_REUSSI IN ('Y', 'N')),
    CONSTRAINT FK_JOURNAL_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEURS(ID_UTILISATEUR)
);

-- =============================================
-- Table: PARAMETRES
-- Configuration de l'application
-- =============================================
CREATE TABLE PARAMETRES (
    CLE VARCHAR2(100) PRIMARY KEY,
    VALEUR VARCHAR2(4000),
    DESCRIPTION VARCHAR2(500),
    MODULE VARCHAR2(50),
    EST_MODIFIABLE CHAR(1) DEFAULT 'Y',
    DATE_CREATION TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATE_MODIFICATION TIMESTAMP,
    UTILISATEUR_MODIFICATION VARCHAR2(100),
    CONSTRAINT CHK_PARAM_MODIFIABLE CHECK (EST_MODIFIABLE IN ('Y', 'N'))
);

-- =============================================
-- CrÃ©ation des index
-- =============================================
-- Index pour les recherches frÃ©quentes
CREATE INDEX IDX_ABONNE_NOM_PRENOM ON ABONNES(NOM, PRENOM);
CREATE INDEX IDX_ABONNE_EMAIL ON ABONNES(EMAIL);
CREATE INDEX IDX_ACTIVITE_NOM ON ACTIVITES(NOM);
CREATE INDEX IDX_EMPLOYE_NOM_PRENOM ON EMPLOYES(NOM, PRENOM);
CREATE INDEX IDX_INSCRIPTION_ABONNE ON INSCRIPTIONS(ID_ABONNE);
CREATE INDEX IDX_INSCRIPTION_ACTIVITE ON INSCRIPTIONS(ID_ACTIVITE);
CREATE INDEX IDX_INSCRIPTION_STATUT ON INSCRIPTIONS(STATUT);
CREATE INDEX IDX_INSCRIPTION_DATE ON INSCRIPTIONS(DATE_INSCRIPTION);
CREATE INDEX IDX_JOURNAL_DATE ON JOURNAUX_ACTIVITE(DATE_HEURE_ACTION);
CREATE INDEX IDX_JOURNAL_UTILISATEUR ON JOURNAUX_ACTIVITE(ID_UTILISATEUR);

-- =============================================
-- DÃ©clencheurs pour l'auto-incrÃ©mentation
-- =============================================
CREATE OR REPLACE TRIGGER TRG_ABONNES_ID
BEFORE INSERT ON ABONNES
FOR EACH ROW
BEGIN
    IF :NEW.ID_ABONNE IS NULL THEN
        :NEW.ID_ABONNE := SEQ_ID_ABONNE.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACTIVITES_ID
BEFORE INSERT ON ACTIVITES
FOR EACH ROW
BEGIN
    IF :NEW.ID_ACTIVITE IS NULL THEN
        :NEW.ID_ACTIVITE := SEQ_ID_ACTIVITE.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INSCRIPTIONS_ID
BEFORE INSERT ON INSCRIPTIONS
FOR EACH ROW
BEGIN
    IF :NEW.ID_INSCRIPTION IS NULL THEN
        :NEW.ID_INSCRIPTION := SEQ_ID_INSCRIPTION.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MATERIELS_ID
BEFORE INSERT ON MATERIELS
FOR EACH ROW
BEGIN
    IF :NEW.ID_MATERIEL IS NULL THEN
        :NEW.ID_MATERIEL := SEQ_ID_MATERIEL.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLES_ID
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
    IF :NEW.ID_ROLE IS NULL THEN
        :NEW.ID_ROLE := SEQ_ID_ROLE.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_JOURNAUX_ID
BEFORE INSERT ON JOURNAUX_ACTIVITE
FOR EACH ROW
BEGIN
    IF :NEW.ID_JOURNAL IS NULL THEN
        :NEW.ID_JOURNAL := SEQ_ID_JOURNAL.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_UTILISATEURS_ID
BEFORE INSERT ON UTILISATEURS
FOR EACH ROW
BEGIN
    IF :NEW.ID_UTILISATEUR IS NULL THEN
        :NEW.ID_UTILISATEUR := SEQ_ID_UTILISATEUR.NEXTVAL;
    END IF;
END;
/

-- =============================================
-- Insertion des rÃ´les par dÃ©faut
-- =============================================
INSERT INTO ROLES (CODE_ROLE, LIBELLE, DESCRIPTION) 
VALUES ('ADMIN', 'Administrateur', 'AccÃ¨s complet au systÃ¨me');

INSERT INTO ROLES (CODE_ROLE, LIBELLE, DESCRIPTION) 
VALUES ('GERANT', 'GÃ©rant', 'Gestion complÃ¨te des opÃ©rations du club');

INSERT INTO ROLES (CODE_ROLE, LIBELLE, DESCRIPTION) 
VALUES ('SECRETAIRE', 'SecrÃ©taire', 'Gestion des inscriptions et des abonnÃ©s');

INSERT INTO ROLES (CODE_ROLE, LIBELLE, DESCRIPTION) 
VALUES ('MONITEUR', 'Moniteur', 'Gestion des activitÃ©s et des cours');

INSERT INTO ROLES (CODE_ROLE, LIBELLE, DESCRIPTION) 
VALUES ('MEMBRE', 'Membre', 'AccÃ¨s membre standard');

-- =============================================
-- Insertion de l'utilisateur administrateur par dÃ©faut
-- Le mot de passe sera mis Ã  jour par l'application avec un hachage sÃ©curisÃ©
-- =============================================
INSERT INTO UTILISATEURS (NOM_UTILISATEUR, MOT_DE_PASSE_HASH, EMAIL, COMPTE_ACTIF)
VALUES ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'admin@smartsummerclub.tn', 'Y');

INSERT INTO UTILISATEURS_ROLES (ID_UTILISATEUR, ID_ROLE, DATE_DEBUT)
VALUES (1, 1, SYSDATE);

-- =============================================
-- Insertion des paramÃ¨tres par dÃ©faut
-- =============================================
INSERT INTO PARAMETRES (CLE, VALEUR, DESCRIPTION, MODULE, EST_MODIFIABLE)
VALUES ('NOM_CLUB', 'Smart Summer Club', 'Nom du club', 'GENERAL', 'Y');

INSERT INTO PARAMETRES (CLE, VALEUR, DESCRIPTION, MODULE, EST_MODIFIABLE)
VALUES ('ADRESSE_CLUB', '123 Avenue Habib Bourguiba', 'Adresse du club', 'GENERAL', 'Y');

INSERT INTO PARAMETRES (CLE, VALEUR, DESCRIPTION, MODULE, EST_MODIFIABLE)
VALUES ('TELEPHONE_CLUB', '+216 70 000 000', 'TÃ©lÃ©phone du club', 'GENERAL', 'Y');

INSERT INTO PARAMETRES (CLE, VALEUR, DESCRIPTION, MODULE, EST_MODIFIABLE)
VALUES ('EMAIL_CONTACT', 'contact@smartsummerclub.tn', 'Email de contact', 'GENERAL', 'Y');

-- =============================================
-- Validation des modifications
-- =============================================
COMMIT;

-- =============================================
-- VÃ©rification de la crÃ©ation des objets
-- =============================================
SET SERVEROUTPUT ON SIZE 1000000
DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== VÃ©rification de la crÃ©ation des tables ===');
    DBMS_OUTPUT.PUT_LINE('=== Table Creation Verification ===');
    
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ABONNES';
    DBMS_OUTPUT.PUT_LINE('ABONNES table created: ' || CASE WHEN v_count > 0 THEN 'YES' ELSE 'NO' END);
    
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ACTIVITES';
    DBMS_OUTPUT.PUT_LINE('ACTIVITES table created: ' || CASE WHEN v_count > 0 THEN 'YES' ELSE 'NO' END);
    
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'EMPLOYES';
    DBMS_OUTPUT.PUT_LINE('EMPLOYES table created: ' || CASE WHEN v_count > 0 THEN 'YES' ELSE 'NO' END);
    
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'INSCRIPTIONS';
    DBMS_OUTPUT.PUT_LINE('INSCRIPTIONS table created: ' || CASE WHEN v_count > 0 THEN 'YES' ELSE 'NO' END);
    
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'MATERIELS';
    DBMS_OUTPUT.PUT_LINE('MATERIELS table created: ' || CASE WHEN v_count > 0 THEN 'YES' ELSE 'NO' END);
    
    DBMS_OUTPUT.PUT_LINE('===================================');
    
    -- Check constraints
    DBMS_OUTPUT.PUT_LINE('=== Constraints Verification ===');
    FOR c IN (SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE 
              FROM USER_CONSTRAINTS 
              WHERE TABLE_NAME IN ('ABONNES', 'ACTIVITES', 'EMPLOYES', 'INSCRIPTIONS', 'MATERIELS')
              ORDER BY TABLE_NAME, CONSTRAINT_TYPE) 
    LOOP
        DBMS_OUTPUT.PUT_LINE(c.TABLE_NAME || ' - ' || c.CONSTRAINT_NAME || ' (' || c.CONSTRAINT_TYPE || ')');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('==================================');
END;
/

-- Show all created tables with row counts
SELECT 
    TABLE_NAME,
    (SELECT COUNT(*) FROM USER_TABLES T2 WHERE T2.TABLE_NAME = T1.TABLE_NAME) AS EXISTS_FLAG,
    (SELECT COUNT(*) FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE '%' || T1.TABLE_NAME || '%') AS HAS_SEQUENCE,
    (SELECT COUNT(*) FROM USER_TRIGGERS WHERE TABLE_NAME = T1.TABLE_NAME) AS HAS_TRIGGER
FROM USER_TABLES T1
WHERE T1.TABLE_NAME IN ('ABONNES', 'ACTIVITES', 'EMPLOYES', 'INSCRIPTIONS', 'MATERIELS')
ORDER BY TABLE_NAME;